version: 2
updates:
  - package-ecosystem: terraform
    directories: ["/bootstrap", "/landing-zone", "/modules/*"]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        update-types: [minor, patch]
